# Alembic Configuration File

[alembic]
# path to migration files
script_location = db/migrations

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path
# if not set, uses the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# leave as `None` if timestamps should be in local time.
sqlalchemy.url = driver://user:pass@localhost/dbname

# migration script encoding
sqlalchemy_encoding = utf-8

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
